canton_zurich:
  api_base: https://parlzhcdws.cmicloud.ch
  files_api:
    path: /cdws/Files
  indexes:
    Behoerden:
      section: parlzh2
      path: /cdws/Index/BEHOERDEN
    SitzungenDetail:
      section: parlzh3
      path: /cdws/Index/SITZUNGENDETAIL
    Geschaeft:
      section: parlzh5
      path: /cdws/Index/GESCHAEFT
    Mitglieder:
      section: parlzh2
      path: /cdws/Index/MITGLIEDER
    Parteien:
      section: parlzh2
      path: /cdws/Index/PARTEIEN
    Wahlkreise:
      section: parlzh2
      path: /cdws/Index/WAHLKREISE
    Direktion:
      section: parlzh5
      path: /cdws/Index/GESCHAEFT_DIREKTION
    Geschaeftsart:
      section: parlzh5
      path: /cdws/Index/GESCHAEFT_GESCHAEFTSART
    Gremiumtyp:
      section: parlzh3
      path: /cdws/Index/GREMIUMTYP
    KRVersand:
      section: parlzh1
      path: /cdws/Index/KRVERSAND
    Ablaufschritte:
      section: parlzh5
      path: /cdws/Index/ABLAUFSCHRITTE
        
city_zurich:
  api_base: https://www.integ.gemeinderat-zuerich.ch
  files_api:
    path: /api/files
  indexes:
    geschaeft:
      path: /api/geschaeft
    dokument:
      path: /api/dokument
    departement:
      path: /api/departement
    gremiumsuebersicht:
      path: /api/gremiumsuebersicht
    gremium:
      path: /api/gremium
    gremiumstyp:
      path: /api/gremiumstyp
    geschaeftsart:
      path: /api/geschaeftsart
    partei:
      path: /api/partei
    pendentbei:
      path: /api/pendentbei
    geschaeftvorstoesser:
      path: /api/geschaeftsvorstoesser
    kontakt:
      path: /api/kontakt
    behoerdenmandat:
      path: /api/behoerdenmandat
    wohnkreis:
      path: /api/wohnkreis
    wahlkreis:
      path: /api/wahlkreis
    ablaufschritt:
      path: /api/ablaufschritt
    referendum:
      path: /api/referendum
    sitzung:
      path: /api/sitzung
    ratspost:
      path: /api/ratspost
